python modified_get_friend_network.py out1 friend_network1 &
python modified_get_friend_network.py out2 friend_network2 &
python modified_get_friend_network.py out3 friend_network3 &
python modified_get_friend_network.py out4 friend_network4 &
python modified_get_friend_network.py out5 friend_network5 &
python modified_get_friend_network.py out6 friend_network6 &
python modified_get_friend_network.py out7 friend_network7 &
python modified_get_friend_network.py out8 friend_network8 &
python modified_get_friend_network.py out9 friend_network9 &
python modified_get_friend_network.py out10 friend_network10 &
python modified_get_friend_network.py out11 friend_network11 &
python modified_get_friend_network.py out12 friend_network12 &
python modified_get_friend_network.py out13 friend_network13 &
python modified_get_friend_network.py out14 friend_network14 &
python modified_get_friend_network.py out15 friend_network15 &
python modified_get_friend_network.py out16 friend_network16 &
python modified_get_friend_network.py out17 friend_network17 &
python modified_get_friend_network.py out18 friend_network18 &
python modified_get_friend_network.py out19 friend_network19 &
python modified_get_friend_network.py out20 friend_network20 &
python modified_get_friend_network.py out21 friend_network21 &
python modified_get_friend_network.py out22 friend_network22 &
python modified_get_friend_network.py out23 friend_network23 &
python modified_get_friend_network.py out24 friend_network24 &
python modified_get_friend_network.py out25 friend_network25 &
python modified_get_friend_network.py out26 friend_network26 &
python modified_get_friend_network.py out27 friend_network27 &
python modified_get_friend_network.py out28 friend_network28 &
python modified_get_friend_network.py out29 friend_network29 &
python modified_get_friend_network.py out30 friend_network30 &
python modified_get_friend_network.py out31 friend_network31 &
python modified_get_friend_network.py out32 friend_network32 &
python modified_get_friend_network.py out33 friend_network33 &
