python modified_get_friends.py uqkMhSl0BlU7BZ1WnbFOoTptq 4O3VB4RDgf0CFCBnU2kqaT252MpByzFQKqlLbARSRfcCaNRWzx unique_mention_ids.txt mention1 &
python modified_get_friends.py s7coXB8rObEkx6fdGh2xwm1C4 zmfbaWMGgkJtGkf0bv3NYC6h9VLQcLnioRhGYsjeMg4kVIkJog unique_user2_ids.txt user1 
